CSS:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
    - CSScomb
HTML:
  beautifiers:
    - Pretty Diff
    - JS-Beautify
EJS:
  beautifiers:
    - Pretty Diff
    - JS-Beautify
HTML+ERB: !<tag:yaml.org,2002:js/undefined> ''
JSON:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
JavaScript:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
    - ESLint
Markdown:
  beautifiers:
    - Prettier
Mustache:
  beautifiers:
    - JS-Beautify
Python:
  beautifiers:
    - Black
    - YAPF
Vue:
  beautifiers:
    - Prettier
TypeScript:
  beautifiers:
    - Prettier
    - Pretty Diff
    - TSLint
SQL:
  beautifiers:
    - sqlformat
Swig:
  beautifiers:
    - Pretty Diff
Twig: !<tag:yaml.org,2002:js/undefined> ''
XML:
  beautifiers:
    - Pretty Diff
    - JS-Beautify
