install:
	npm install

# serve with hot reload
dev:
	npm run dev

# build for production with minification
build:
	npm run build

clean:
	npm cache clean --force
	rm -rf node_modules
	rm -rf package-lock.json
	rm -rf dist
