# install dependencies
install:
	yarn install

# serve with hot reload at localhost:3000
dev:
	yarn dev

# build for production and launch server
build:
	yarn build
	yarn start

# generate static project
generate:
	yarn generate
